version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=domain_hq
    network_mode: host
    volumes:
      - ./_volumes/postgres:/var/lib/postgresql/data
      - ./scripts/bootstrap/:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U john -d domain_hq'" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    network_mode: host
    healthcheck:
      test: "curl -f localhost:8080 || false"
      interval: 30s
      timeout: 3s
      retries: 10
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
    depends_on:
      postgres:
        condition: service_healthy

  go-web-finger:
    image: cosmtrek/air
    container_name: go-web-finger
    hostname: go-web-finger
    working_dir: /app
    user: ${HOST_UID}:${HOST_GID}
    command: -c air.toml
    env_file:
      - .env
    volumes:
      - ./:/app
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
    depends_on:
      postgres:
        condition: service_healthy
