version: "3.9"

services:
  go-web-finger:
    image: cosmtrek/air
    container_name: go-web-finger
    hostname: go-web-finger
    working_dir: /app
    user: ${HOST_UID}:${HOST_GID}
    command: -c air.toml
    env_file:
      - .env
    volumes:
      - ./:/app
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"